import type { Metadata } from "next";
import '../styles/globals.scss'
import Header from "@/backbone/header";
import localFont from 'next/font/local'
import Footer from "@/backbone/footer";
import { ReduxProvider } from "@/redux/provider";



const myFont = localFont({ src: './Gordita-Regular.otf' })

export const metadata: Metadata = {
  title: "beije.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
