
import Image from 'next/image'

import FormImage from "../../../../public/login-img.png"
import Link from 'next/link'
import type { Metadata } from "next";
import LoginForm from '@/components/forms/login-form'


export const metadata: Metadata = {
  title: "Giriş Yap | beije.",
  description: "Generated by create next app",
}

const Login = () => {

  return (
    <main className="auth-form">
      <div className="auth-form-wrapper">
        <div className="form-img">
          <Image src={FormImage} alt="Form-image" fill sizes="50vw"  />
        </div>
        <div className="form-content">
          <div className="form-content-wrapper">
            <div className="form-title">
              <p>Merhaba</p>
              <span>beije'e hoş geldin!</span>
            </div>
            <div className="form-group">
              <p className="selected-form select-clr-dark">Giriş Yap</p>
              <p className="disabled-clr-dark">Üyel Ol</p>
            </div>
            <div className="login-opt">
              <Link href={"/"}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <path
                    fill="#4285F4"
                    d="M21.5 11.868a9.7 9.7 0 0 0-.158-1.763h-8.66v3.339h4.959a3.9 3.9 0 0 1-.631 1.493c-.315.452-.724.84-1.202 1.14v2.172h2.96C20.5 16.74 21.5 14.508 21.5 11.87"
                  ></path>
                  <path
                    fill="#34A853"
                    d="M12.682 20.343c2.476 0 4.566-.769 6.086-2.094l-2.96-2.169c-.825.53-1.884.83-3.126.83-2.394 0-4.427-1.524-5.154-3.579H4.479v2.235a8.9 8.9 0 0 0 3.384 3.487 9.6 9.6 0 0 0 4.82 1.29"
                  ></path>
                  <path
                    fill="#FBBC04"
                    d="M7.528 13.331a4.92 4.92 0 0 1 0-3.318V7.776H4.479a8.3 8.3 0 0 0-.979 3.896c0 1.353.335 2.687.979 3.895z"
                  ></path>
                  <path
                    fill="#EA4335"
                    d="M12.682 6.434a5.15 5.15 0 0 1 3.522 1.3l2.622-2.475c-1.662-1.473-3.864-2.283-6.144-2.258a9.6 9.6 0 0 0-4.818 1.29 8.9 8.9 0 0 0-3.385 3.486l3.049 2.235c.727-2.054 2.76-3.578 5.154-3.578"
                  ></path>
                </svg>
                Google
              </Link>
              <Link href={"/"}>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M16.9994 6.00008L13.9996 6.00025C13.4473 6.00028 12.9996 6.448 12.9997 7.00025L12.9998 10.0001L16.9996 9.99985C17.1133 9.99732 17.2212 10.0502 17.2888 10.1417C17.3564 10.2332 17.3754 10.3518 17.3396 10.4598L16.5998 12.6597C16.5316 12.8616 16.3429 12.9981 16.1298 12.9997L13 12.9999L13.0004 20.4995C13.0005 20.7756 12.7766 20.9995 12.5005 20.9995L10.0006 20.9996C9.72452 20.9996 9.50066 20.7758 9.50064 20.4997L9.50021 13.0001L8.0003 13.0002C7.72417 13.0002 7.50031 12.7763 7.5003 12.5003L7.50018 10.5004C7.50017 10.2243 7.724 10.0004 8.00013 10.0004L9.50004 10.0003L9.49987 7.00045C9.49974 4.79144 11.2904 3.00058 13.4994 3.00045L16.9992 3.00025C17.2753 3.00023 17.4992 3.22407 17.4992 3.50019L17.4993 5.50008C17.4993 5.7762 17.2755 6.00006 16.9994 6.00008Z" fill="#3975EA"/>
              </svg>
                Facebook
              </Link>
            </div>
            <hr />
            <LoginForm />
            
          </div>
        </div>
      </div>
    </main>
  )
}

export default Login

